# Generated by Django 5.0.14 on 2026-09-24 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_activitylog_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('BROKEN_CODE', 'Broken Code / Runtime Error'), ('BACKEND_ERROR', 'Backend Server Error (500)'), ('UNRESPONSIVE_UI', 'Unresponsive / Frozen UI'), ('DATABASE_USAGE', 'Database Spikes / Latency'), ('SECURITY_BREACH', 'Security Breach / Suspicious Attempt'), ('NETWORK_FAILURE', 'Network Degradation / Offline Drop')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('severity', models.CharField(default='HIGH', max_length=20)),
                ('email_dispatched', models.BooleanField(default=False)),
                ('recipient', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(default='SYSTEM', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('consent_status', models.CharField(default='ALL', max_length=50)),
                ('necessary', models.BooleanField(default=True)),
                ('analytics', models.BooleanField(default=True)),
                ('functional', models.BooleanField(default=True)),
                ('security', models.BooleanField(default=True)),
                ('disclaimer_acknowledged', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
