# Generated by Django 5.0.14 on 2026-08-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
