# Generated by Django 5.0.14 on 2026-08-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherprofile_account_number_teacherprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
