# Generated by Django 5.0.14 on 2026-08-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_2fa', models.BooleanField(default=True)),
                ('otp_channels', models.JSONField(blank=True, default=list)),
                ('otp_expiry_minutes', models.IntegerField(default=5)),
                ('max_otp_attempts', models.IntegerField(default=3)),
                ('send_welcome_email_with_credentials', models.BooleanField(default=True)),
                ('allow_direct_student_pin_login', models.BooleanField(default=True)),
                ('min_password_length', models.IntegerField(default=8)),
                ('require_special_char', models.BooleanField(default=True)),
                ('require_number', models.BooleanField(default=True)),
                ('password_expiry_months', models.IntegerField(default=6)),
                ('failed_login_lockout_attempts', models.IntegerField(default=5)),
                ('school_name', models.CharField(default='Tare Pet Montessori School', max_length=200)),
                ('short_name', models.CharField(default='TPMS', max_length=50)),
                ('motto', models.CharField(default='Excellence Through Observation & Character', max_length=255)),
                ('official_email', models.EmailField(default='info@tarepet.edu.ng', max_length=254)),
                ('phone', models.CharField(default='+234 803 123 4567', max_length=50)),
                ('address', models.TextField(default='12 Kpansia-Epie Road, Yenagoa, Bayelsa State, Nigeria')),
                ('ministry_reg_no', models.CharField(default='EDU/BY/SCH/2009/0421', max_length=100)),
                ('proprietress', models.CharField(default='Mrs. Tare Pet', max_length=150)),
                ('principal', models.CharField(default='Dr. T. Montessori', max_length=150)),
                ('vice_principal', models.CharField(default='Mr. James Eze', max_length=150)),
                ('accreditations', models.TextField(blank=True, null=True)),
                ('session', models.CharField(default='2025/2026', max_length=50)),
                ('term', models.CharField(default='2nd Term', max_length=50)),
                ('term_start', models.CharField(default='2026-01-12', max_length=50)),
                ('term_end', models.CharField(default='2026-04-04', max_length=50)),
                ('min_pass_mark', models.IntegerField(default=50)),
                ('ca1_weight', models.IntegerField(default=15)),
                ('ca2_weight', models.IntegerField(default=15)),
                ('exam_weight', models.IntegerField(default=70)),
                ('grading_scale', models.JSONField(blank=True, default=dict)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('single_session_per_user', models.BooleanField(default=True)),
                ('rbac_roles', models.JSONField(blank=True, default=dict)),
                ('sms_provider', models.CharField(default='Termii (Nigeria)', max_length=100)),
                ('sms_sender_id', models.CharField(default='TPMS-School', max_length=50)),
                ('sms_balance', models.IntegerField(default=4820)),
                ('notify_results_sms', models.BooleanField(default=True)),
                ('notify_attendance_sms', models.BooleanField(default=True)),
                ('notify_fees_sms', models.BooleanField(default=True)),
                ('notify_cbt_exams', models.BooleanField(default=True)),
                ('late_fee_penalty', models.CharField(default='₦2,000 flat fee after due date', max_length=100)),
                ('scholarship_slots', models.IntegerField(default=10)),
                ('fee_schedules', models.JSONField(blank=True, default=dict)),
                ('portal_language', models.CharField(default='en-NG', max_length=50)),
                ('color_scheme', models.CharField(default='system', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('currency', models.CharField(default='NGN', max_length=20)),
                ('settings_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='address',
            field=models.TextField(blank=True, default='12 Kpansia-Epie Road, Yenagoa, Bayelsa State', null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='admin_id',
            field=models.CharField(blank=True, default='TMS/ADM/2018/001', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True, default='Visionary educational leader with over 18 years of pioneering excellence in Montessori and Nigerian National Curriculum pedagogy. Committed to nurturing intellectual curiosity, ethical character, and academic brilliance across all learners.', null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='blood_group',
            field=models.CharField(blank=True, default='O+', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='committees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(blank=True, default='Executive Governance & Academics', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='direct_extension',
            field=models.CharField(blank=True, default='Ext. 101 (Direct Intercom)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='divisions_supervised',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='dob',
            field=models.CharField(blank=True, default='1978-08-15', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='Mrs. Florence Montessori (Spouse)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, default='+234 802 987 6543', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='office_location',
            field=models.CharField(blank=True, default="Principal's Office Suite, Block A Executive Wing", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='rank',
            field=models.CharField(blank=True, default='Chief Executive Administrator (Super Admin)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='state_of_origin',
            field=models.CharField(blank=True, default='Bayelsa State, Nigeria', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='title',
            field=models.CharField(blank=True, default='School Principal & Chief Administrator', max_length=150, null=True),
        ),
    ]
