# Generated by Django 5.0.14 on 2026-08-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0007_systemsettings_adminprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=50, unique=True)),
                ('division', models.CharField(choices=[('CRECHE_NURSERY', 'Montessori Crèche & Nursery'), ('PRIMARY', 'Montessori Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary (JSS)'), ('SENIOR_SECONDARY', 'Senior Secondary (SS)')], default='PRIMARY', max_length=50)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=40000.0, max_digits=12)),
                ('development_levy', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12)),
                ('books_materials', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('uniform_sports', models.DecimalField(decimal_places=2, default=8000.0, max_digits=12)),
                ('pta_medical', models.DecimalField(decimal_places=2, default=3000.0, max_digits=12)),
                ('exam_levy', models.DecimalField(decimal_places=2, default=2000.0, max_digits=12)),
                ('extra_fees', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('term', models.CharField(default='2nd Term', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₦)')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('class_level', models.CharField(max_length=50)),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('term', models.CharField(default='2nd Term', max_length=20)),
                ('total_billed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_accounts', to='users.studentprofile')),
            ],
            options={
                'ordering': ['class_level', 'student_name'],
            },
        ),
    ]
