# Generated by Django 5.0.14 on 2026-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_cbt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtexam',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved by Admin'), ('PUBLISHED', 'Published to Class'), ('REJECTED', 'Rejected by Admin')], default='DRAFT', max_length=20),
        ),
    ]
