# Generated by Django 5.0.14 on 2026-09-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_cbtexam_status'),
        ('courses', '0002_initial'),
        ('users', '0008_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='class_name',
            field=models.CharField(default='SS1', help_text='Target class (e.g. SS1, SS2, SS3)', max_length=50),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='course_code',
            field=models.CharField(blank=True, default='GEN-101', help_text='Course or Subject Code', max_length=50),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='course_name',
            field=models.CharField(blank=True, default='General Assessment', help_text='Course or Subject Name', max_length=150),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='results_released',
            field=models.BooleanField(default=False, help_text='Whether students can view their detailed exam scores'),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='stream',
            field=models.CharField(default='Science', help_text='Target stream (e.g. Science, Arts, Commercial)', max_length=50),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='teacher_name',
            field=models.CharField(blank=True, default='Assigned Educator', help_text='Teacher Full Name', max_length=150),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Rationale or explanation for correct option', null=True),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image diagram URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cbtexam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_exams', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='cbtexam',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved by Admin'), ('ACTIVE', 'Active / Ongoing'), ('PUBLISHED', 'Published to Class'), ('REJECTED', 'Rejected by Admin'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='cbtexam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cbt_exams', to='users.teacherprofile'),
        ),
    ]
