# Generated by Django 5.0.14 on 2026-09-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_cbtexam_class_name_cbtexam_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtstudentattempt',
            name='auto_paused',
            field=models.BooleanField(default=False, help_text='True if auto-paused/locked due to violations'),
        ),
        migrations.AddField(
            model_name='cbtstudentattempt',
            name='integrity_flags',
            field=models.JSONField(blank=True, default=list, help_text='Proctoring violation logs'),
        ),
        migrations.AddField(
            model_name='cbtstudentattempt',
            name='pause_events',
            field=models.JSONField(blank=True, default=list, help_text='History of pause and lockout intervals'),
        ),
    ]
