# Generated by Django 5.0.14 on 2026-09-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_cbtstudentattempt_auto_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether exam is locked from starting or submitting'),
        ),
    ]
