# Generated by Django 5.0.14 on 2026-08-21 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_teacherprofile_account_number_teacherprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_identifier', models.CharField(db_index=True, max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('stream', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(default='PRESENT', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('marked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance_records', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_code', models.CharField(db_index=True, max_length=100)),
                ('from_class', models.CharField(max_length=50)),
                ('to_class', models.CharField(max_length=50)),
                ('academic_session', models.CharField(default='2026/2027', max_length=50)),
                ('term', models.CharField(default='3rd Term', max_length=50)),
                ('promoted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadsheetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_identifier', models.CharField(db_index=True, max_length=100)),
                ('course_code', models.CharField(db_index=True, max_length=50)),
                ('course_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ca1', models.FloatField(default=0.0)),
                ('ca2', models.FloatField(default=0.0)),
                ('cbt_score', models.FloatField(default=0.0)),
                ('exam', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('term', models.CharField(default='1ST_TERM', max_length=20)),
                ('session', models.CharField(default='2026/2027', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadsheet_scores', to='users.studentprofile')),
            ],
            options={
                'ordering': ['course_code'],
                'unique_together': {('student_identifier', 'course_code', 'term', 'session')},
            },
        ),
    ]
