# Generated by Django 5.0.14 on 2026-07-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade_level', models.CharField(default='Primary 1', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('enrollment_limit', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('audio', 'Audio'), ('external_link', 'External Link'), ('quiz', 'Quiz')], default='video', max_length=20)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_time', models.PositiveIntegerField(default=15, help_text='Estimated time in minutes')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('essay', 'Essay')], default='multiple_choice', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of option strings or key-value choices')),
                ('correct_answer', models.CharField(help_text='Correct option or exact answer key', max_length=255)),
                ('points', models.FloatField(default=10.0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Time limit in minutes (0 for no limit)')),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('passing_score', models.FloatField(default=70.0, help_text='Passing score percentage')),
                ('shuffle_questions', models.BooleanField(default=True)),
            ],
        ),
    ]
